<?php
$pfHelper = Mage::helper("payfort/data");
?>

<?php if($pfHelper->isMerchantPageMethod()):?>
<div class="pf-iframe-background" id="div-pf-iframe" style="display:none">
    <div class="pf-iframe-container">
        <span class="pf-close-container">
            <i class="fa fa-times-circle pf-iframe-close" onclick="pfClosePopup()"></i>
        </span>
        <i class="fa fa-spinner fa-spin pf-iframe-spin"></i>
        <div class="pf-iframe" id="pf_iframe_content"></div>
    </div>
</div>
<style>
.pf-iframe-background{
    position: fixed;
    z-index: 999;
    width: 100%;
    height: 100%;
    text-align: center;
    top: 0;
    left: 0;
    background: rgba(0,0,0,0.8);
    z-index: 99999
}
.pf-iframe-container{
    position: relative;
    z-index: 99999999
}
iframe#payfort_merchant_page {
    width:80% !important;
    min-height:100% !important;
}
.pf-close-container{
    display:block;
    text-align:center;
    margin:1em auto;
}
.pf-iframe-close{
    font-size: 1.7em;
    color: #fff;
    cursor: pointer
}
.pf-iframe-spin{
    font-size: 3em;
    color: #fff;
    display: block;
    margin: 1em auto;
    cursor: default
}
</style>
<?php endif; ?>


